language: java
jdk:
  - oraclejdk8
  - openjdk8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mercurial libsqlite3-dev python-dev python-virtualenv samtools bedtools
install:
  - mvn -version
  - mvn clean package install -DskipTests -Dgpg.skip
after_failure:
 - echo "Tests failed, dumping all logs."
 - cat /tmp/**/bootstrap-log/*
script: travis_wait mvn test -B
